name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  Deploy:
    runs-on: ubuntu-latest
    needs: Build

    steps:

      - name: Deploy
        run: echo "Not deploying to production..."