name: Linter, Tests, Build and Deploy

on:
  push:
    branches: [ "*" ]

  workflow_dispatch:

jobs:
  Linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Lint Action
        uses: wearerequired/lint-action@v2.3.0

  Tests:
    runs-on: ubuntu-latest
    needs: Linter

    steps:
      - uses: actions/checkout@v3

      # install npm dependencies
      - name: Install dependencies
        run: npm install

      # Runs tests
      - name: Run test
        run: npm test

  Build:
    runs-on: ubuntu-latest
    needs: Tests

    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm run build --if-present