name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  GenerateChangelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload changelog
        uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: changelog.txt

  CreateRelease:
    needs: GenerateChangelog
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }} # Set job output
    steps:
      - uses: actions/checkout@v2
      - name: Check if prerelease
        id: check_prerelease
        run: |
          if [[ "${{ github.ref }}" == *alpha ]] || [[ "${{ github.ref }}" == *beta ]]; then
            echo "::set-output name=prerelease::true"
          else
            echo "::set-output name=prerelease::false"
          fi
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_RELEASE }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: ${{ steps.check_prerelease.outputs.prerelease }}

  UploadChangelog:
    needs: CreateRelease
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download changelog
        uses: actions/download-artifact@v2
        with:
          name: changelog
      - name: Debug
        run: |
          echo "Upload URL: ${{ needs.CreateRelease.outputs.upload_url }}"
          echo "Asset Path: ./changelog.txt"
      - name: Upload changelog to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_ADDCHANGELOG }}
        with:
          upload_url: ${{ needs.CreateRelease.outputs.upload_url }} # Use job output
          asset_path: ./changelog.txt
          asset_name: changelog.txt
          asset_content_type: text/plain

  Deploy:
    needs: UploadChangelog
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: ${{ secrets.REMOTE_PORT }}
          script: /scripts/deployCommandCraftor.sh