name: Generate Changelog
on:
  release:
    types: [published, prereleased]

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y git
      - name: Generate changelog
        run: |
          PREVIOUS_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          git log --pretty=format:"%s" $PREVIOUS_TAG..HEAD > changelog.txt
      - name: Upload changelog
        uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: changelog.txt