name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  Tests:
    runs-on: ubuntu-latest
    needs: Linter

    steps:
      - uses: actions/checkout@v3

      # install npm dependencies
      - name: Install dependencies
        run: npm install

      # Runs tests
      - name: Run test
        run: npm test